/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const LucideFileText: typeof import('~icons/lucide/file-text')['default']
  const LucideGlobe2: typeof import('~icons/lucide/globe2')['default']
}
