name: crm

services:
  mariadb:
    image: mariadb:10.8
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Tempor10.6
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-admin}
    volumes:
      - mariadb-data:/var/lib/mysql

  redis:
    image: redis:alpine

  frappe:
    build:
      context: ..
      dockerfile: Dockerfile
    image: crm-app
    command: bash /workspace/init.sh
    environment:
      SHELL: /bin/bash
      FRAPPE_SITE_NAME: ${FRAPPE_SITE_NAME:-crm.localhost}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-admin}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-admin}
      MYSQL_HOST: mariadb
      REDIS_CACHE: redis://redis:6379
      REDIS_QUEUE: redis://redis:6379
      REDIS_SOCKETIO: redis://redis:6379
    working_dir: /workspace
    volumes:
      - ../:/workspace:delegated
    depends_on:
      - mariadb
      - redis
    ports:
      - "8003:8000"
      - "9003:9000"

volumes:
  mariadb-data: