dbfilename redis_queue.rdb
dir /Users/rafaelrnzo/Proj/Proj/summon/crm-summon/my-frappe-bench/config/pids
pidfile /Users/rafaelrnzo/Proj/Proj/summon/crm-summon/my-frappe-bench/config/pids/redis_queue.pid
bind 127.0.0.1
port 11000

aclfile /Users/rafaelrnzo/Proj/Proj/summon/crm-summon/my-frappe-bench/config/redis_queue.acl
