dbfilename redis_cache.rdb
dir /Users/rafaelrnzo/Proj/Proj/summon/crm-summon/my-frappe-bench/config/pids
pidfile /Users/rafaelrnzo/Proj/Proj/summon/crm-summon/my-frappe-bench/config/pids/redis_cache.pid
bind 127.0.0.1
port 13000
maxmemory 819mb
maxmemory-policy allkeys-lru
appendonly no

save ""


aclfile /Users/rafaelrnzo/Proj/Proj/summon/crm-summon/my-frappe-bench/config/redis_cache.acl
